import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../globals.css";
import { TanstackQuery } from "@/providers/queryClientProvider";
import { SideBar } from "@/components/SideBar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find a Friend",
  description: "Generated by create next app",
};

export default function PetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={nunito.className}>
        <TanstackQuery>
          <main className="w-full h-full flex flex-row">
            <SideBar />
            {children}
          </main>
        </TanstackQuery>
      </body>
    </html>
  );
}
