import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { TanstackQuery } from "@/providers/queryClientProvider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find a Friend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={nunito.className}>
        <TanstackQuery>{children}</TanstackQuery>
      </body>
    </html>
  );
}
