import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../globals.css";
import { LogoWithText } from "@/components/Logo/LogoWithText";
import { Friends } from "@/components/Friends";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find a Friend",
  description: "Generated by create next app",
};

export default function OrgLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={nunito.className}>
          <main className="w-full h-screen flex flex-row justify-evenly items-center">
            <section className="w-[488px] h-[661px] flex flex-col items-center justify-between pt-28 pb-9 rounded-3xl bg-coral-500">
              <LogoWithText />

              <Friends width="384" />
            </section>

            {children}
          </main>
      </body>
    </html>
  );
}
