import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../../globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find a Friend",
  description: "Generated by create next app",
};

export default function OrgProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={nunito.className}>
          <main className="w-full h-screen flex flex-row justify-evenly items-center">
            {children}
          </main>
      </body>
    </html>
  );
}
